### ISSUE TITLE
Old platforms prevent `readlink /proc/self/exe` from non-main threads on release build

### ISSUE THREAD

**Issue by canyie** [canyie/Magisk#5]
Device: Samsung SM-J3110, and more
Android version: 5/6
Magisk version name:
Magisk version code: 25201

Tested AVD and it works just fine.
The latest working version might be 24314/24315. Since 25000 it does no longer work
topjohnwu#6257 

Other issue: topjohnwu#6488

**Comment by hhihhio** [comment]
same with my samsung J7 2015 android 6, problem happen from magisk 24

**Comment by canyie** [comment]
https://stackoverflow.com/questions/28590831/android-permission-denied-when-reading-proc-self-exe-from-non-main-thread

**Comment by Unknown78** [comment]
@maingocvinh  Please do as per canyie instruction. [(source)](https://github.com/topjohnwu/Magisk/issues/6257#issuecomment-1242646250)

> I need a log to find out why.
> 
> 1. Install ADB on your PC. Turn on "USB debugging“ in developer settings.
> 2. Connect your phone to your PC. Allow USB debugging if your phone asks for it.
> 3. Open cmd, type "adb logcat -c" and enter.
> 4. Type "adb logcat > app.log"
> 5. Install release-build app, open it, it should stuck at the Magisk logo
> 6. Wait one minute, press "Ctrl + C" in the cmd window, and upload `app.log`
